### ISSUE TITLE
AttributeError: module 'pycocotools' has no attribute '__version__'

### ISSUE THREAD

**Issue by jialeli1** [open-mmlab/mmdetection3d#102]
I have installed mmdet and mmdet3d according to the instructions, but I encountered the following problems when preparing kitti data.
I run this line:

> $ python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti

And I got this error:  

> assert pycocotools.__version__ >= '12.0.2' AttributeError: module 'pycocotools' has no attribute '__version__'

I can't find a solution on the Internet, I hope that you could give me a hint.

**Comment by Tai-Wang** [comment]
> I have installed mmdet and mmdet3d according to the instructions, but I encountered the following problems when preparing kitti data.
> I run this line:
> $ python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
> 
> And I got this error:
> assert pycocotools.**version** >= '12.0.2' AttributeError: module 'pycocotools' has no attribute '**version**'
> 
> I can't find a solution on the Internet, I hope that you could give me a hint.

It is because the up-to-date mmdet uses the modified pycocotools forked from original package, namely `mmpycocotools`, which should be installed automatically with mmdet. The reason for this error may be an ambiguous import linking due to your previously installed original pycocotools.

The solution is `pip uninstall pycocotools` and check whether you can import pycocotools and it has the `version` attribute.

**Comment by jialeli1** [comment]
> > I have installed mmdet and mmdet3d according to the instructions, but I encountered the following problems when preparing kitti data.
> > I run this line:
> > $ python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
> > And I got this error:
> > assert pycocotools.**version** >= '12.0.2' AttributeError: module 'pycocotools' has no attribute '**version**'
> > I can't find a solution on the Internet, I hope that you could give me a hint.
> 
> It is because the up-to-date mmdet uses the modified pycocotools forked from original package, namely `mmpycocotools`, which should be installed automatically with mmdet. The reason for this error may be an ambiguous import linking due to your previously installed original pycocotools.
> 
> The solution is `pip uninstall pycocotools` and check whether you can import pycocotools and it has the `version` attribute.

Thank you for your reply. Your analysis is correct. I solved this problem by running this line:
> pip install --force-reinstall pycocotools@git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools
Please refer to this [issue ](https://github.com/open-mmlab/mmdetection/issues/3426#issue-667257345) in mmdet.  After this, I checked again, it still exists mmpycocotools and pycocotools, but it works.

**Comment by jialeli1** [comment]
However, there is another problem here:

> (open-mmlab) lijiale@ImageLab:~/mmdet_install/mmdetection3d$ python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
> Generate info. this may take several minutes.
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3712/3712, 196.8 task/s, elapsed: 19s, ETA:     0s
> Kitti info train file is saved to data/kitti/kitti_infos_train.pkl
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3769/3769, 209.2 task/s, elapsed: 18s, ETA:     0s
> Kitti info val file is saved to data/kitti/kitti_infos_val.pkl
> Kitti info trainval file is saved to data/kitti/kitti_infos_trainval.pkl
> Kitti info test file is saved to data/kitti/kitti_infos_test.pkl
> create reduced point cloud for training set
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3712/3712, 239.2 task/s, elapsed: 16s, ETA:     0s
> create reduced point cloud for validatin set
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3769/3769, 271.0 task/s, elapsed: 14s, ETA:     0s
> create reduced point cloud for testing set
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 7518/7518, 275.0 task/s, elapsed: 27s, ETA:     0s
> Create GT Database of KittiDataset
> Traceback (most recent call last):
>   File "tools/create_data.py", line 172, in <module>
>     out_dir=args.out_dir)
>   File "tools/create_data.py", line 32, in kitti_data_prep
>     with_mask=(version == 'mask'))
>   File "/home/lijiale/mmdet_install/mmdetection3d/tools/data_converter/create_gt_database.py", line 187, in create_groundtruth_database
>     dataset = build_dataset(dataset_cfg)
>   File "/home/lijiale/mmdet_install/mmdetection3d/mmdet3d/datasets/builder.py", line 37, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
>     return obj_cls(**args)
> TypeError: __init__() got an unexpected keyword argument 'use_valid_flag'
> (open-mmlab) lijiale@ImageLab:~/mmdet_install/mmdetection3d$ 
>

**Comment by Tai-Wang** [comment]
It seems to be introduced by a recent commit (PR #87 ) related to nuscenes dataset. Thanks for your bug report. We will fix it ASAP.

**Comment by jialeli1** [comment]
> It seems to be introduced by a recent commit (PR #87 ) related to nuscenes dataset. Thanks for your bug report. We will fix it ASAP.

Is there a previous version available if I only want to work with the KITTI dataset?

**Comment by ZwwWayne** [comment]
Fixed in #106

**Comment by HongxuZhu** [comment]
pip list | grep pycocotools
pip uninstall pycocotools
pip uninstall mmpycocotools
pip install mmpycocotools

**Comment by swaggywilliam** [comment]
Sorry, I didn't solve the problem as I follow the solution : pip uninstall pycocotools and **only reinstall mmpycocotools**. Because I got a new ['ValueError'](https://github.com/open-mmlab/mmdetection3d/issues/650) when I only install mmpycocotools, What's even more frustrating for me is the solution to the  'ValueError' is to **[install mmpycocotoolos and pycocotools==2.0.1](https://github.com/open-mmlab/mmdetection3d/issues/650#issuecomment-862136000)**？？？

> pip list | grep pycocotools pip uninstall pycocotools pip uninstall mmpycocotools pip install mmpycocotools
