### ISSUE TITLE
FLOPs for PointPillars 

### ISSUE THREAD

**Issue by Code-Gratefully** [open-mmlab/mmdetection3d#981]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help. - Yes
2. The bug has not been fixed in the latest version. - Yes

**Describe the bug**
When attempting to run flops on PointPillars, there is a bug.

**Reproduction**
1. What command or script did you run?

```
python tools/analysis_tools/get_flops.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py --shape 40000 4 --modality point
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I first tried the custom config and then I revert to the default config

3. What dataset did you use?
KITTI 

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
Python: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
CUDA available: True
GPU 0: NVIDIA RTX A6000
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.5.3
MMCV: 1.3.11
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.4
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.0+2e08308

2. You may add addition that may be helpful for locating the problem, such as

**Error traceback**
If applicable, paste the error trackback here.

```
/home/e/.local/lib/python3.8/site-packages/mmdet/core/anchor/builder.py:15: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  warnings.warn(
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 95, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 85, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/home/e/.local/lib/python3.8/site-packages/mmcv/cnn/utils/flops_counter.py", line 104, in get_model_complexity_info
    _ = flops_model(batch)
  File "/home/e/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/e/mmdetection3d/mmdet3d/models/detectors/single_stage.py", line 47, in forward_dummy
    x = self.extract_feat(points)
  File "/home/e/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 45, in extract_feat
    x = self.middle_encoder(voxel_features, coors, batch_size)
  File "/home/e/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/e/.local/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/e/mmdetection3d/mmdet3d/models/middle_encoders/pillar_scatter.py", line 34, in forward
    return self.forward_batch(voxel_features, coors, batch_size)
  File "/home/e/mmdetection3d/mmdet3d/models/middle_encoders/pillar_scatter.py", line 86, in forward_batch
    voxels = voxel_features[batch_mask, :]
IndexError: too many indices for tensor of dimension 1
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by LucidusC** [comment]
The issue seems caused by voxelizing [0,0,0,0] x N points, causing an inconsistent count between voxel_features and coords. 

Issue resolved by modifying a code in MMCV repo:

```mmcv/cnn/utils/flops_counter.py`:94``


        try:
            #batch = torch.ones(()).new_empty(
            #    (1, *input_shape),
            #    dtype=next(flops_model.parameters()).dtype,
            #    device=next(flops_model.parameters()).device)
            batch = torch.rand( (1, *input_shape) ,
                dtype=next(flops_model.parameters()).dtype,
                device=next(flops_model.parameters()).device)
        except StopIteration:
            # Avoid StopIteration for models which have no parameters,
            # like `nn.Relu()`, `nn.AvgPool2d`, etc.
            batch = torch.ones(()).new_empty((1, *input_shape))


I shall be much appreciated if @Tai-Wang or @ZCMax can kindly work on a more permanent solution.  Thanks!

**Comment by stidk** [comment]
I also encountered the same problem. Do you have any good solutions? If so, I will be very grateful.

**Comment by ZCMax** [comment]
Error fixed by #1075.

**Comment by erwangccc** [comment]
@Tai-Wang @ZCMax Hi, could we change batchsize to another number, such as 4,8,12?

**Comment by cadip92** [comment]
I still get the same error message when I try to calculate FLOPs for PointPillars as shown here #3028.
Request assistance @ZCMax @Tai-Wang @Code-Gratefully
